project_name: gomo

env:
  - CGO_ENABLED=0

release:
  prerelease: auto
  draft: true
  name_template: "Gomo 📐 {{ .Tag }}"

before:
  hooks:
    - go mod tidy -compat=1.18

builds:
  - <<: &build_defaults
      binary: bin/gomo
      main: ./
      ldflags:
        - -X main.version={{ .Tag }}
        - -X main.buildDate={{ .Env.BuildDate }}

    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64, arm ]

  - <<: *build_defaults
    id: linux
    goos: [ linux ]
    goarch: [ amd64, arm64, arm, 386 ]

  - <<: *build_defaults
    id: windows
    goos: [ windows ]
    goarch: [ amd64, arm64, arm, 386 ]

  - <<: *build_defaults
    id: freebsd
    goos: [ freebsd ]
    goarch: [ amd64, arm64, arm, 386 ]

archives:
  - id: unix
    builds: [ macos, linux, freebsd ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Tag }}_{{ .Arch }}"

    wrap_in_directory: "true"
    replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: "false"
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: gomo
    homepage: https://github.com/abdfnx/gomo
    bindir: /usr
    file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Arch }}"
    description: "📐 Simple Golang multi modules tool"
    formats:
      - apk
      - deb
      - rpm

brews:
  - goarm: 6
    tap:
      owner: abdfnx
      name: homebrew-tap
    homepage: "https://github.com/abdfnx/gomo"
    description: "📐 Simple Golang multi modules tool"
    license: MIT

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-next"
